// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbzDuNU-74ruFe95yE20wUE2BOJqqKEM',
    appId: '1:89244440005:android:65cf6709b42a2447fb27ac',
    messagingSenderId: '89244440005',
    projectId: 'internet-magazine-39743',
    databaseURL: 'https://internet-magazine-39743-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'internet-magazine-39743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBB0iaPz4XRwGckpgR6l21d2DcMuLyf3M',
    appId: '1:89244440005:ios:b21af5752fb5992dfb27ac',
    messagingSenderId: '89244440005',
    projectId: 'internet-magazine-39743',
    databaseURL: 'https://internet-magazine-39743-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'internet-magazine-39743.appspot.com',
    iosClientId: '89244440005-5r1c0caholk0dj9n5o815eu9e05trg7s.apps.googleusercontent.com',
    iosBundleId: 'com.av.internetMagazine',
  );
}
